"""add annotation_color to movies

Revision ID: 0b4847344ead
Revises: 1d777a2bd309
Create Date: 2026-07-09 12:39:58.240043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b4847344ead'
down_revision: Union[str, Sequence[str], None] = '1d777a2bd309'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Step 1: add the column as nullable first so existing rows don't error
    op.add_column('movies', sa.Column('annotation_color', sa.String(length=7), nullable=True))
    
    # Step 2: fill in the default gold color for all existing rows
    op.execute("UPDATE movies SET annotation_color = '#C17F24'")
    
    # Step 3: now that all rows have a value, enforce NOT NULL
    op.alter_column('movies', 'annotation_color', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'annotation_color')
    # ### end Alembic commands ###
